---
title: "Grafico tema 3"
author: "Ferran Medina Mompó, Rubén Sierra Punter y Hugo Lucas Mateos"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)

# Importamos los datos
data <- read_csv("data/owid-covid-data.csv")

# Seleccionamos los países en los que estamos interesados
paises_deseados <- c("Spain", "Germany", "Japan", "United States", "Canada", "France", "Italy", "United Kingdom")
df_1 <- data %>%
  filter(location %in% paises_deseados)

# Crear la gráfica
grafica_covid <- ggplot(df_1, aes(x = date, y = total_deaths, color = location)) + 
  geom_line() +

  #Implementamos función para que la linea de España sea más gruesa y de color rojo.
  
  geom_line(data=subset(df_1,location=="Spain"),aes(group=location), color="red", size=1.5)
  labs(title = "Total de muertes por COVID-19 en varios países (Grupo R)",
       x = "Fecha",
       y = "Total de muertes") +
  theme_minimal()
  
  #Establecemos el periodo de tiempo que queremos que nos muestre.
  lim <- as.Date(c("2020-02-13", "2024-03-04"))
  
  #Le decimos el formato en el que queremos poner la fecha dentro de la gráfica.
  
  grafica_covid + scale_x_date(limits = lim, date_labels = "%b %d, %Y")




```

```{r}
library(ggplot2)
library(plotly)
library(dplyr)

# Definir países de interés
paises <- c("United States", "Italy", "France", "Germany", "Canada", "Japan", "United Kingdom", "Spain")

# Colores para cada país
colores <- c("United States" = "purple1", "United Kingdom" = "deeppink", "Japan" = "azure4", 
              "Canada" = "darkred", "Italy" = "darkturquoise", "Germany" = "chartreuse4", 
              "France" = "orange4", "Spain" = "red")


# Filtrar datos para países de interés
df_1 <- data %>%
  filter(location %in% paises) %>%
  select(date, location, new_deaths_smoothed_per_million)


# Filtrar datos específicamente para España, ya que este país debe tener unas 
# características distintas a los demás paises (color y grosor).

df_esp <- data %>%
  filter(location == "Spain") %>%
  select(date, location, new_deaths_smoothed_per_million)

# Crear gráfico 

grafico <- ggplot(df_1, aes(x = date, y = new_deaths_smoothed_per_million, color = location)) +
  geom_hline(yintercept=c(2,4,6,8,10,12,14,16,18), color="gray", linetype="dotted")+
  
  geom_line(size = 0.55) +
  geom_line(data = df_esp, size = 1.25) +
  scale_color_manual(values = colores) +
  theme(legend.position = "none") +
  theme_classic()+
  theme(axis.line.x = element_blank(), axis.line.y=element_blank())+
  scale_y_continuous(limits=c(0,NA), breaks= seq(0,18, by=2)) +
  
  scale_x_date(date_breaks = "40 weeks", date_labels =  "%b %d %Y") +
  labs(y = "Número de muertes por millón de personas", x = "Fecha", 
       title = "Nuevas muertes diarias por COVID-19 por millón de personas")

grafico

```
